Support waas 1.9
Tangany/waas-js-sdk pull request #76
Opened 2022-01-31 08:27 UTC by lenabl

- Extend wallet information for btc and eth
- Add "amount" as optional parameter for btc transactions, add optional sweep parameter for fee estimation
- Extend transaction estimation for btc and eth with new properties
- Add Tezos functionality
- Add tests for Tezos integration

Resolves #73

2022-02-03 13:36 UTC, kepikoi commented on src/xtz-wallet.spec.ts
> +            assert.strictEqual(postStub.withArgs(`${baseUrl}/delegate-async`, sampleAddress).callCount, 1);
My unit test run is failing at this line. Can you please check this?

2022-02-03 13:43 UTC, kepikoi commented on test/tezos.e2e.js
> +	it("should cancel current delegate", async function () {
I would rather _set_ an new delegate on the temporary wallet created in the second unit to retain some degree of idempotency in the E2E test

2022-02-03 13:49 UTC, kepikoi commented on src/xtz-contract-wallet.ts
> +     * @param config Smart contract configuration
```suggestion
     * @param config - Smart contract configuration
```

2022-02-03 13:51 UTC, kepikoi commented on src/interfaces/tezos.ts
> +export interface ITezosOperationStatusOutput {
Please describe the interfaces via JSDoc annotations (compare ethereum.ts or bitcoin.ts)

2022-02-03 14:06 UTC, kepikoi commented on test/bitcoin.e2e.js
> -	});
Please add a sweep estimation test to the E2E suite

2022-02-03 14:16 UTC, kepikoi commented on src/waas.ts
>  }
Please add the missing Tezos header configuration options: `tangany-tezos-gas-limit`, `tangany-tezos-storage-limit`, `tangany-tezos-operation-confirmations`. 
Also add those as module exports to `src/index.ts`

2022-02-03 14:17 UTC, kepikoi requested changes
- Please update the change log (under ## [Unreleased])
- Update the `Available configuration headers` in `readme.md` with the Tezos configuration options (`tezosOperationConfirmations` etc.)
- Add Tezos code samples below `### More examples` to `readme.md` 
- Remove the deprecated (and meanwhile decommissioned) Ethereum ERC20 methods `send`, `approve`, `transferFrom`, `burn`, and `mint` as well as the dependent `getRecipientsData` method

2022-02-04 12:12 UTC, lenabl commented
Made the requested changes:

* Fix failing unit test
* Add new e2e tests
* Add missing headers
* Remove deprecated methods
* Update readme and changelog

2022-02-07 11:27 UTC, lenabl commented on src/xtz-wallet.spec.ts
> +            assert.strictEqual(postStub.withArgs(`${baseUrl}/delegate-async`, sampleAddress).callCount, 1);
Resolved in 0254db89c7fbdcd62a3e8a12cb6470cb03e434eb

2022-02-07 11:29 UTC, lenabl commented on test/tezos.e2e.js
> +	it("should cancel current delegate", async function () {
Resolved in eac9da2fbd567b7f5e1fea254544805c2d0788a7

2022-02-07 11:30 UTC, lenabl commented on src/interfaces/tezos.ts
> +export interface ITezosOperationStatusOutput {
Resolved in e8c2a5a001829670d9d83c62500b64541fea6bff

2022-02-07 11:31 UTC, lenabl commented on test/bitcoin.e2e.js
> -	});
Resolved in 5499b30a882e75be3226526c0dc8520fac4240ed

2022-02-07 11:32 UTC, lenabl commented on src/waas.ts
>  }
Resolved in 3b12e580d9510745b14c2cf68fe2894cffa5ea1c

2022-02-07 11:37 UTC, kepikoi approved these changes

2022-02-07 11:45 UTC, merged