Update sdk to work with waas 1.12
Tangany/waas-js-sdk pull request #88
Opened 2022-10-17 15:02 UTC by lenabl

- update sdk to be compatible with waas 1.12

resolves #87

2022-10-24 09:15 UTC, christianemmert commented
The `should read transaction events for a specific contract` test case in `ethereum-read.e2e.js` fails due to a problem in WaaS itself. The error occurs in https://github.com/Tangany/waas/blob/f5968e8a01ad17778ea00d61e10ef5ccd562224b/src/classes/anyblock/anyblock.ts#L294 because sometimes the `event.args["value.hex"]` that gets returned from Anyblock is not a string but an array of values. As such the check `value.startsWith("0x-")` throws the error `value.startsWith is not a function`.

2022-10-25 10:43 UTC, christianemmert commented
> The `should read transaction events for a specific contract` test case in `ethereum-read.e2e.js` fails due to a problem in WaaS itself. The error occurs in https://github.com/Tangany/waas/blob/f5968e8a01ad17778ea00d61e10ef5ccd562224b/src/classes/anyblock/anyblock.ts#L294 because sometimes the `event.args["value.hex"]` that gets returned from Anyblock is not a string but an array of values. As such the check `value.startsWith("0x-")` throws the error `value.startsWith is not a function`.
> 
> @mazlinho does it make sense to create an issue for that bug?

A new [Issue](https://github.com/Tangany/waas/issues/1000) for WaaS was created. The e2e test case in the sdk was changed to fetch a `Transfer` event instead.

2022-10-25 14:35 UTC, gpa requested changes

2022-10-25 14:35 UTC, gpa commented on src/request.ts
> +        return url;
Theoretically we need to encode values with `encodeURIComponent` but I think our allowed inputs range doesn't need encoding ☑️

2022-10-26 08:38 UTC, christianemmert commented on src/interfaces/common.ts
> +    } | RequestStatus )[];
[d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

2022-10-26 08:38 UTC, christianemmert commented on readme.md
> +	const request = new Request(api);
[d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

2022-10-26 08:38 UTC, christianemmert commented on src/iterables/auto-pagination/resource-iterable.spec.ts
> +        assert((item as any).links)
[d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

2022-10-26 08:39 UTC, christianemmert commented on src/request.ts
> +            } else if (Object.prototype.toString.call(value) === '[object Date]') {
[d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

2022-10-26 08:39 UTC, christianemmert commented on src/request.ts
> +    public list(params?: IRequestSearchParams, options?: ISearchOptions): Promise<IRequestStatusesResponse> | RequestPageIterable | RequestIterable {
[d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

2022-10-26 08:39 UTC, christianemmert commented on src/waas.ts
>   * @param options.bitcoinMaxFeeRate - Maximum allowed fee rate in satoshi per byte for a Bitcoin transaction
[d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

2022-10-26 08:39 UTC, christianemmert commented on test/request.e2e.js
> +			assert.ok(requestId.includes(request.requestId))
[d2ae7fd](https://github.com/Tangany/waas-js-sdk/pull/88/commits/d2ae7fd2c0f486c09175c1e0e541946bb19c596f)

2022-10-26 09:03 UTC, gpa commented on src/interfaces/common.ts
> +export interface ISearchResponse<T = any> extends IPaginationResponse {
Is this type accessible to package clients? If so, this would be theoretically a breaking change, not sure if we need to care about this case though, probably not. Also do we need the new interface`ISearchResponseWithLinks` ? seems like every extends overrides the list type anyway with links, for example `export interface IEventSearchResponse extends ISearchResponse {
    list: {
        event: string;
        links: IHateoasLink<"event">[];
    }[];
}`

2022-10-26 10:12 UTC, christianemmert commented on src/interfaces/common.ts
> +export interface ISearchResponse<T = any> extends IPaginationResponse {
`ISearchResponseWithLinks` is only used and overwritten by other interfaces which then are accessible to clients. So no breaking change.
[2deadc8](https://github.com/Tangany/waas-js-sdk/pull/88/commits/2deadc89b397c67a73479831da429bec97a84ade)

2022-10-26 10:12 UTC, christianemmert commented on src/interfaces/common.ts
> +export interface ISearchResponse<T = any> extends IPaginationResponse {
`ISearchResponseWithLinks` is only used and overwritten by other interfaces which then are accessible to clients. So no breaking change.
[2deadc8](https://github.com/Tangany/waas-js-sdk/pull/88/commits/2deadc89b397c67a73479831da429bec97a84ade)

2022-10-26 15:27 UTC, gpa approved these changes

2022-10-26 15:28 UTC, merged